
services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: karkibase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - minimart-net

  backend:
    image: rupesh69/minimart-api:v2
    container_name: minimart-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env        
    environment:
      DB_URI: "postgres://myuser:mypassword@db:5432/karkibase"
    depends_on:
      - db
    networks:
      - minimart-net

volumes:
  pgdata:

networks:
  minimart-net:
    driver: bridge
